### ISSUE TITLE
Error in tuple unpacking

### ISSUE THREAD

**Issue by mihaeladuta** [OxfordRSE/L2Gv2#17]
l2gv2/embedding/svd.py:171:8: W0632: Possible unbalanced tuple unpacking with sequence defined at line 594 of scipy.sparse.linalg._eigen.lobpcg.lobpcg: left side has 3 labels, right side has 2 values (unbalanced-tuple-unpacking)

**Comment by abhidg** [comment]
I think this is happening because pylint can't detect a conditional return statement which changes the return type: `retResidualNormsHistory=True` should return the residuals, but otherwise the default behaviour of lobpcg is to return a 2-tuple: https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.lobpcg.html
